export const colors = {
    primary: '#1155CC',
    primary_light: '#E1EAF9',
    secondary: '#50cebf',
    secondary_light: '#EAF9F7',
    tertiary: '#EDBB26',
    black: '#3a3a3a',
    white: '#fff',
    background: '#f4f4f6',
    grey_placeholder: '#E5E5E5',
    gray_background_social: '#E5E5E5',
    grey_background: '#f9f9f9',
    grey_line: '#c3c3c3',
    lightGrey: '#f9f9f9',
    darkGrey: '#0c0c0c',
    danger: '#ff5252',
    success: '#4ecdc4',
    warning: '#ffe66d',
    info: '#6ab04c',
    light: '#f7f1e3',
    dark: '#130f40',
    transparent: 'transparent',
    red: '#FF0000',
};

