export const colors = {
    primary: '#ED7661',
    primary_light: '#F5BBB1',
    secondary: '#FFF1EF',
    tertiary: '#B75443',
    black: '#3A3A3A',
    white: '#F9F9F9',
    background: '#F4F4F4',
    input_background: '#D9D9D9',
    grey_placeholder: '#E5E5E5',
    grey_line: '#B4B4B4',
    lightGrey: '#F9F9F8',
    danger: '#BD0B0B',
    transparent: 'transparent',
    text_grey: '#D9D9D9',
    text_button: '#FFFFFF',
    facebook: '#4267B2',
    gmail: '#DD4B39',
    };

